CREATE TABLE `TB_MAIN_MENU` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '메인메뉴 테이블 ID, PRIMARY KEY',
  `MENU_NM` varchar(20) DEFAULT NULL COMMENT '메뉴 이름',
  `MENU_COMMENT` varchar(200) DEFAULT NULL COMMENT '메뉴 설명',
  `URL` varchar(200) DEFAULT NULL COMMENT '메뉴 URL',
  `ACTIVE_YN` tinyint(4) DEFAULT '1' COMMENT '메뉴 활성화 여부',
  `SUB_MENU_GRP` varchar(10) DEFAULT NULL COMMENT '메뉴 그룹',
  `SORT` int(11) DEFAULT NULL COMMENT '메뉴 정렬순서',
  `REG_DATE` date DEFAULT NULL COMMENT '메뉴 등록날짜',
  `UPT_DATE` date DEFAULT NULL COMMENT '메뉴 수정날짜',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `TB_MBR` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '회원테이블의 ID, PRIMARY KEY'
  `LOGIN_ID` varchar(20) DEFAULT NULL COMMENT '로그인 ID',
  `PWD` varchar(256) DEFAULT NULL COMMENT '비밀번호',
  `ACTIVE_YN` char(1) DEFAULT 'N' COMMENT '활성화여부',
  `GROUP_ALIAS` varchar(20) DEFAULT NULL COMMENT '회원그룹',
  `AUTH_ID` int(11) DEFAULT NULL COMMENT '권한ID (자세한권한관리를 위해 추가 현재사용안함)',
  `REG_DATE` date DEFAULT NULL COMMENT '회원가입날짜',
  `UPT_DATE` date DEFAULT NULL COMMENT '회원정보 수정날짜',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_IDX_MBR1` (`LOGIN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `TB_MENU_SET_USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '메뉴 세팅하는 테이블의 ID, PRIMARY KEY',
  `LOGIN_ID` varchar(20) DEFAULT NULL COMMENT '로그인 아이디',
  `SET_MENU_NO` varchar(200) DEFAULT NULL COMMENT '로그인 아이디에 세팅할 메뉴 ID (코마로 구분 ,)',
  `REG_DATE` date DEFAULT NULL COMMENT '메뉴를 처음 등록한 날짜',
  `UPT_DATE` date DEFAULT NULL COMMENT '메뉴 세팅을 수정한 날짜',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_IDX_MBR1` (`LOGIN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `TB_APPS` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '앱테이블의 ID, PRIMARY KEY',
  `THUMBNAIL_NAME` VARCHAR(100) NULL COMMENT '앱 썸네일 이미지 파일명',
  `APP_NAME` VARCHAR(200) NULL COMMENT '앱 아름',
  `APP_DIVISION` VARCHAR(200) NULL COMMENT '앱 구분 예) gsh, gsc, gsr....',
  `REG_DATE` DATE NULL COMMENT '앱 등록날짜',
  `UPT_DATE` DATE NULL COMMENT '앱 수정날짜',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_IDX_APPS1` (`APP_NAME`),
  INDEX `IDX_APPS1` (`APP_NAME` ASC, `APP_DIVISION` ASC)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
